name: abax
description: Virtual Supermarket Assistant
version: 2.0.1+4

environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  amazon_cognito_identity_dart_2: ^3.0.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  xml: ^6.0.1
  #google_sign_in: ^5.0.7
  #flutter_login_facebook: ^1.6.2
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  url_launcher: 6.0.20
  flutter_barcode_scanner: ^2.0.0
  #flutter_native_splash: ^2.2.9
  #flutter_echarts: ^2.4.0
  #charts_painter: ^3.0.0
  #fl_chart: ^0.55.2
  #graphic: ^1.0.0
  #flutter_charts: ^0.5.0
  fl_animated_linechart: ^1.1.6
  vertical_barchart: ^2.0.0+2

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Audiowide
      fonts: 
        - asset: assets/fonts/AudiowideRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
